export const COMPANY_NAME = 'companyName'
export const COMPANY_NICK = 'companyNick'
export const COMPANY_URL = 'companyUrl'
export const COMPANY_EMAIL = 'companyEmail'
export const COMPANY_PHONE = 'companyPhone'
export const COMPANY_ADDRESS_LINE_1 = 'companyAddressLine1'
export const COMPANY_ADDRESS_LINE_2 = 'companyAddressLine2'

export const NON_ADMINS = 'non-admins'
export const SELF_REGISTRATION = 'self-registration'
export const LIMIT_INVITES = 'limit-invites'
export const MISSION_STATEMENTS = 'missionStatements'
export const DEFAULT_TIME_ZONE = 'defaultTimeZone'

export const VALUES_FIELD = 'values'
export const TAGS_FIELD = 'tags'
export const BILLING_EMAIL = 'billing_email'
